# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
application:
  uploadFolder: D:/THUTHUY/bmbe/image

logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    pbm.com.exchange: DEBUG


spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/stuffexchange?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database: mysql
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.stuffexchange@gmail.com #Replace this field with your Gmail username.
    password: ahubjzlcvzbvienr #Replace this field with your Gmail password/App password.
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
  sleuth:
    sampler:
      probability: 1 # report 100% of traces
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true

server:
  port: 8082

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 100 # Number of objects in each cache entry
  # CORS is only enabled by default with the "dev" profile
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200,http://localhost:4000,https://45.122.223.101:4000,http://45.122.223.101:4000'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: NGUyYmJmOTgxZTY4MDQyNjE2YTI1NjgwMjY5ZTQ2NjlmODJlMGQxODA4M2U3OTVhNGVjZDU5YWY0M2NiODQzMzdjNWE4NmYyNTBmYjgwOWI4ZjI5MDMyOWM3ZDdmYTM5MWVkZTg2Mzk2MmQ1NjA3OGE2NWQ0MzBiYWYwODFkNmU=
        # Token is valid 24 hours
        token-validity-in-seconds: 2592000
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://127.0.0.1:8082
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:
twilio:
  USE_OTP: false
  ACCOUNT_SID: 'AC717febc2f6f291c8e8d0eb6afe028074'
  AUTH_TOKEN: '9ef54ffa6fd9a80d4b4692f2433e5c3f'
  SERVICE_ID: 'VA3e5ee9be3da08b9bebe9ad236bd99d15'
  CHANNEL: 'sms'

avatar:
  default:
    user: 'http://zeusbe.emclab.tech/api/app/image/download/33'

mail:
  default:
    admin: 'swapnow.ad@gmail.com'

app:
  firebase-configuration-file: notification-69f68-firebase-adminsdk-14n8e-f21edaf456.json
